import Head from 'next/head';
import Navbar from '../components/navbar';
import styles from '@/styles/Home.module.css';

export default function About() {
  return (
    <>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <p>
          Laborum magna sint aliquip exercitation in irure ad adipisicing velit
          sint ea pariatur in. Reprehenderit cupidatat duis velit aute. Amet ea
          non nostrud id nisi irure eu proident irure elit cupidatat sint ad. Ad
          in aute qui excepteur dolore sit mollit dolor ad aliqua culpa.
          Deserunt ut veniam occaecat elit. Enim sunt eiusmod mollit elit labore
          reprehenderit incididunt in non veniam anim commodo eiusmod. Commodo
          irure pariatur sit nostrud magna cupidatat. Reprehenderit anim in
          nulla dolore minim ea in culpa dolore ullamco. Eiusmod aute dolore
          magna quis reprehenderit in aliqua consectetur consectetur. Cillum
          labore laborum laboris irure exercitation. Lorem amet eu fugiat aute
          officia esse incididunt magna et aliquip do. Ex voluptate Lorem irure
          adipisicing do ex incididunt. Officia consequat aute occaecat duis ad
          dolor aute enim exercitation nulla excepteur. Commodo reprehenderit
          deserunt eiusmod ad dolore exercitation enim qui mollit cupidatat sunt
          cillum esse ex. Sint enim est nulla dolore mollit. Sunt tempor id et
          eu nisi labore ut fugiat ut laborum culpa aute non consectetur. Duis
          pariatur commodo pariatur duis anim voluptate Lorem deserunt duis
          ipsum pariatur exercitation. Non ut dolor nostrud laborum pariatur
          dolor cupidatat. Excepteur laborum nisi Lorem ut laboris esse nisi.
          Nostrud dolor do cillum aute aliquip tempor proident laborum commodo
          nostrud et. Ut labore pariatur quis occaecat nisi. Enim eu sit do anim
          qui aliqua. Reprehenderit qui irure deserunt minim aliqua enim
          voluptate non esse sunt in officia esse cillum. Deserunt ad laboris
          sunt aliqua anim duis non aliqua fugiat enim reprehenderit est cillum.
          Ea laboris eiusmod quis aliqua reprehenderit enim officia enim officia
          et eu. Ut pariatur esse eiusmod sint mollit nisi ea nulla non cillum
          labore ex anim. Sunt culpa ea Lorem deserunt reprehenderit aute ea
          aute in nisi incididunt velit. Incididunt non consequat duis sunt.
          Culpa cillum pariatur Lorem sint cupidatat magna anim excepteur.
          Tempor eiusmod incididunt laborum anim. Veniam nostrud laboris quis
          commodo reprehenderit nisi Lorem consectetur commodo nostrud dolor
          occaecat cupidatat. Exercitation nisi labore sit amet minim Lorem.
          Occaecat sit fugiat sint laboris in id culpa nostrud minim pariatur.
          Elit irure aliquip laborum minim id ex officia id in excepteur quis
          do. Lorem consequat est tempor in deserunt cillum quis ullamco
          exercitation. Ea pariatur dolor ea proident cupidatat consequat do.
          Qui aute ea qui do. Dolor quis laborum ipsum ullamco aute esse.
          Pariatur est commodo consectetur consequat commodo est consequat id
          minim laboris. Amet nostrud est commodo anim veniam non minim nulla
          velit in do labore. Non proident do elit nostrud consectetur
          adipisicing incididunt amet elit minim esse cillum Lorem. Dolore enim
          sint pariatur aute ad magna elit aute culpa. Amet sit aliqua elit
          reprehenderit nulla. Elit et ullamco velit ut duis ipsum laborum
          exercitation duis esse ex. Anim Lorem cillum ad anim eu reprehenderit
          non esse minim ullamco officia. Lorem enim non commodo ullamco
          deserunt aute amet Lorem in non incididunt laborum. Est sit consequat
          ullamco cupidatat excepteur cupidatat aliquip ex duis in aliqua. Sint
          do aliquip esse adipisicing ex non. In ullamco ea tempor ea. Occaecat
          reprehenderit consectetur culpa nisi ad aliquip magna est aliqua velit
          ea. Consectetur dolor exercitation sit ut consectetur reprehenderit
          exercitation deserunt nulla. Ut ea ut deserunt irure deserunt
          reprehenderit commodo tempor et pariatur. Consequat nostrud sunt qui
          mollit exercitation cupidatat aliquip sunt in nostrud consequat aute
          id. Cillum amet reprehenderit non anim amet in dolore minim in
          pariatur quis ipsum. Irure laboris commodo nostrud culpa velit aliqua.
          Tempor reprehenderit ullamco elit minim minim elit proident sint
          adipisicing aute mollit culpa id. Ullamco in ea est commodo do
          pariatur excepteur consectetur ex excepteur ad. Anim aliqua elit
          consequat eiusmod excepteur eiusmod irure. Consectetur est do cillum
          ad laborum. Ipsum ea deserunt reprehenderit ullamco. Exercitation
          mollit velit aliquip et occaecat aliqua consequat dolor laboris do ea
          adipisicing consectetur. Aliquip voluptate nostrud fugiat incididunt
          nisi est dolor minim officia. Do exercitation laborum nostrud esse ut
          minim irure ullamco aliqua eu aute laborum cupidatat. Eu consequat
          irure est in eiusmod exercitation cillum. Consequat ut excepteur
          laboris reprehenderit exercitation excepteur labore occaecat irure
          occaecat proident. Deserunt laboris laboris nulla quis veniam. Ullamco
          aliquip duis laboris in exercitation nulla culpa. Velit ut aute non
          minim. Sit amet eiusmod deserunt velit irure dolore cupidatat est
          magna officia. Esse ea sunt commodo excepteur ullamco sunt labore id
          id. Enim tempor anim ullamco occaecat proident magna. Sunt aliquip
          consequat adipisicing eiusmod irure irure adipisicing culpa ad duis
          occaecat aliqua amet. Velit nisi nulla esse amet. Quis sint est mollit
          eiusmod labore nostrud eu ullamco. Ea in ea est do eu quis ipsum duis
          cupidatat. Quis cillum consectetur adipisicing id aliquip sint labore.
          Laborum et elit amet irure ut sint aliquip velit. Veniam quis non
          minim deserunt do proident veniam ea eu quis incididunt. Aliqua nulla
          nisi amet labore reprehenderit qui excepteur. Do irure nisi ex eiusmod
          consequat consectetur sunt aute voluptate quis excepteur aliquip.
          Excepteur qui duis elit exercitation culpa. Id reprehenderit voluptate
          id laboris cillum laborum sint commodo. Sunt elit occaecat incididunt
          dolor cillum magna aute id consectetur eu eu adipisicing sint quis. Eu
          aliqua Lorem minim do est minim irure deserunt adipisicing eiusmod
          cupidatat. Amet et anim irure proident est. Sit ea reprehenderit
          reprehenderit voluptate do reprehenderit. Mollit occaecat est
          cupidatat est duis eiusmod sit fugiat enim in. In nulla reprehenderit
          qui tempor proident labore elit. Cillum nulla voluptate excepteur
          labore sit esse laborum. Anim consequat mollit exercitation ullamco
          quis tempor irure duis excepteur cillum. Cupidatat cillum do ad
          voluptate reprehenderit id elit fugiat. Minim in ullamco qui aute
          enim. Elit enim labore adipisicing esse nulla eu aliqua ut consectetur
          ex reprehenderit cupidatat duis mollit. Lorem minim laboris nostrud
          commodo ex ipsum. Consequat ea id nostrud et. Amet dolor officia
          tempor labore. Ipsum ullamco nostrud excepteur minim. Voluptate velit
          dolore cillum elit nostrud occaecat aliqua. Laboris id cupidatat nisi
          qui sunt cupidatat. Mollit cillum occaecat qui sit eiusmod cupidatat
          id qui aliquip cillum aliquip sit fugiat. Eiusmod irure magna
          consectetur culpa eu aliqua adipisicing commodo aliquip. Incididunt
          est aute magna elit officia ut ullamco ad non exercitation mollit elit
          aute reprehenderit. Non in adipisicing aliqua cupidatat Lorem dolore
          minim dolor tempor irure duis elit consectetur. Cupidatat excepteur
          est cupidatat nulla cillum sit in. Commodo do non ex amet ad laborum
          in esse id pariatur. Excepteur quis quis in nulla consequat proident
          cillum id sit qui voluptate nostrud velit dolore. Minim ad sunt aute
          sunt non nulla nulla deserunt reprehenderit mollit irure fugiat in.
          Quis dolor dolor laborum esse veniam consequat sint officia eiusmod.
          Fugiat dolor culpa laborum pariatur ipsum occaecat cupidatat ea. Ea
          irure aute cupidatat officia aliqua voluptate dolore do do qui ut
          laboris cillum. Aliquip quis nostrud pariatur ullamco consequat ipsum
          duis ad occaecat anim eu proident. Ad est nisi elit aliqua laboris
          exercitation cillum mollit ad velit anim adipisicing aute fugiat. Ut
          mollit incididunt quis fugiat culpa nostrud commodo nostrud tempor
          amet sit ex aliqua adipisicing. Officia tempor aliqua nisi anim non
          occaecat non laboris pariatur velit. Sunt ullamco sint eu amet fugiat
          quis consequat esse. Dolor reprehenderit minim eu dolor. Ut pariatur
          excepteur consequat exercitation Lorem consequat incididunt nulla
          ipsum cupidatat. Fugiat reprehenderit adipisicing deserunt non id
          mollit anim proident dolor mollit eu labore commodo. Laborum nostrud
          fugiat laborum occaecat minim. Cillum consequat mollit aliqua ut est
          eu. Non ut culpa adipisicing elit dolor sint nisi qui enim.
          Adipisicing aliquip exercitation magna duis. Lorem non Lorem culpa
          esse exercitation est magna ut amet veniam sint Lorem exercitation ea.
          Eiusmod nulla irure occaecat sunt et et eiusmod consectetur consequat
          velit do nostrud esse. Proident mollit eiusmod reprehenderit non
          proident in aliqua pariatur laboris adipisicing aliquip enim. Aute
          ullamco veniam commodo excepteur deserunt sunt deserunt laboris
          exercitation eu anim eiusmod nisi. Irure in cillum mollit qui magna
          fugiat. Culpa laboris dolor reprehenderit nulla eu adipisicing
          pariatur esse. In quis velit deserunt cupidatat elit incididunt.
          Adipisicing cupidatat aliqua est ad enim adipisicing. Deserunt non
          Lorem esse velit cillum. Irure labore cillum consequat reprehenderit
          ipsum ut. Sint proident excepteur ullamco veniam commodo mollit irure
          sunt nostrud minim. Aliquip pariatur duis laborum laboris irure Lorem
          id dolor pariatur ipsum reprehenderit quis dolor duis. Aliquip
          exercitation reprehenderit proident irure elit sit consectetur sunt
          cillum aute nulla deserunt esse consectetur. Veniam labore cupidatat
          dolor exercitation duis ipsum ut esse dolor Lorem eiusmod ut. Aliqua
          qui culpa ipsum ipsum commodo proident. Ullamco sit dolor nostrud
          excepteur labore non. Est quis anim eu sit aliqua minim culpa culpa
          adipisicing in. Anim nisi deserunt magna exercitation ad pariatur
          nostrud. Occaecat deserunt nulla ipsum eiusmod adipisicing duis velit
          velit minim. Sunt excepteur culpa ipsum ut culpa ex reprehenderit. Sit
          sit ea enim aliquip nisi. Commodo Lorem duis sint pariatur quis. Velit
          voluptate ullamco Lorem amet exercitation. Dolore incididunt in qui
          excepteur cillum do. Occaecat aliquip consectetur commodo consequat
          commodo magna magna esse nostrud in enim esse. Proident mollit magna
          adipisicing magna ut consequat minim elit ipsum non et dolore eiusmod
          cupidatat. Sint in deserunt deserunt mollit deserunt. Commodo officia
          voluptate labore veniam incididunt tempor do ex laboris et fugiat
          adipisicing voluptate. Quis enim consectetur culpa commodo veniam est
          do ex et proident id ipsum amet. Do aute esse magna fugiat ea. Ad
          officia irure elit consequat adipisicing. Sunt non Lorem eu laborum
          est proident elit eiusmod laboris velit. Ipsum labore ullamco nostrud
          nisi nulla cupidatat quis ullamco ad culpa. Tempor mollit deserunt
          esse consequat esse veniam velit excepteur do. Ullamco non pariatur
          tempor elit irure eu laborum laborum cupidatat consectetur. Duis aute
          consequat laborum elit cillum amet occaecat aliqua non do proident
          consequat ea laborum. Consectetur ut duis incididunt proident. Tempor
          aute commodo ad ea. Reprehenderit irure cillum minim culpa do qui id
          in ut cillum id. Et commodo fugiat dolore mollit aliqua minim laborum
          ad nostrud reprehenderit labore do nostrud magna. Est cillum ex culpa
          in laborum eu. Nulla quis et excepteur qui. Consectetur culpa nisi do
          sit ad non. Consequat aute est proident Lorem. Tempor officia
          consequat excepteur sint aliqua veniam. Sint proident enim nulla amet
          pariatur veniam Lorem fugiat. Commodo eiusmod proident occaecat
          aliquip incididunt ad tempor voluptate cupidatat consequat deserunt
          nulla ea quis. Ullamco aute deserunt non reprehenderit ea aute eu
          nulla incididunt ea do enim fugiat. Non laboris nisi cillum sint
          deserunt consequat velit. Duis reprehenderit voluptate sint ut ullamco
          pariatur qui culpa veniam laboris laborum nisi anim. Aliquip id
          cupidatat irure mollit aliquip laboris. Commodo elit id irure do
          laboris incididunt id incididunt tempor duis laborum. Id do fugiat
          deserunt ex culpa consectetur elit. Reprehenderit laboris nisi aliquip
          Lorem velit. Ut id esse laboris dolore eu nostrud pariatur
          exercitation sint duis ut ex. Reprehenderit voluptate ex reprehenderit
          Lorem culpa aute ea ullamco occaecat cillum qui nostrud consectetur
          est. Culpa nostrud amet reprehenderit adipisicing dolore sint eiusmod
          eu eiusmod nostrud duis amet et. Consectetur cillum nulla quis et
          eiusmod reprehenderit. Commodo aliqua laboris laboris nulla est est
          fugiat ad proident qui nulla proident voluptate irure. Occaecat
          excepteur duis culpa consectetur consectetur dolor anim do sunt dolore
          velit nisi eu magna. Et culpa nisi labore aute dolore cillum nostrud
          laborum non. Pariatur et cillum dolore labore id dolore labore.
          Nostrud adipisicing eiusmod aute non officia fugiat voluptate amet
          officia eu duis esse eu ullamco. Aute occaecat nisi voluptate mollit
          duis esse culpa quis non. Lorem magna eiusmod elit consequat in
          officia mollit dolor cillum eiusmod amet anim laborum. Ipsum pariatur
          proident incididunt commodo dolore ipsum. Deserunt reprehenderit
          adipisicing incididunt voluptate quis.
        </p>
      </main>
    </>
  );
}
