import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Navbar from '../components/navbar';

const citations = () => {
  return (
    <>
      <Head>
        <title>trg5</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <section className={styles.section}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit
          recusandae iste nihil sequi facilis unde necessitatibus? Debitis
          architecto reprehenderit eum provident. Assumenda, error sit quaerat
          iste tempore fuga adipisci ipsa.
        </section>
      </main>
    </>
  );
};

export default citations;
